### ISSUE TITLE
Not letting me share shaders?

### ISSUE THREAD

**Issue by Tenome** [stromcon/emusak-ui#66]
I just started using this program, so I'm not entirely clear on a few things (like how active it is -- I presume it relies on lots of users using the program in order to be useful for sharing saves and shaders). I successfully downloaded some shaders, but it looks like it's not letting my share some that aren't in the Emusak database. Does it require a certain amount of shaders in order to share?

![8815d617f9 1](https://user-images.githubusercontent.com/12216081/119430029-03f3c100-bcde-11eb-8483-41f69cf932e0.png)

**Comment by stromcon** [comment]
Indeed ! Submissions are manually reviewed and it is very time xonsuming, so there is a threshold : u can't do a share if your local shaders count does not surpass emusak Shaders by at least 100

**Comment by stromcon** [comment]
There is also a limit to 1 share per hour per user on the backend side to avoid spam

**Comment by stromcon** [comment]
@Tenome I added a threshold indicator in emusak, if you are on windows just restart the software. I hope it will be more clear for users
