### ISSUE TITLE
mods descriptions?

### ISSUE THREAD

**Issue by Owyn** [stromcon/emusak-ui#79]
how do I see what each mod does before I download them (or after?)?

![image](https://user-images.githubusercontent.com/1309656/120926991-e6642580-c6e7-11eb-9075-74df8280f08d.png)

**Comment by stromcon** [comment]
Hey there ! Thanks for your feedback. Currently mods description is not implemented, it is a huge work to upload every mod, for every game, for every version and for every country (mods are not the same for US / EU / ASIA) and it is very time consuming to track them all and it will be a full time job to also maintain mod description. Currently most of bowser fury mods are coming from TheBoy181 https://github.com/theboy181/switch-ptchtxt-mods/tree/main/Super%20Mario%203D%20World%20%2B%20Bowser's%20Fury/010028600EBDA000/1.0.0 and u can ask in his discord what they do.

**Comment by Owyn** [comment]
Tried disable Dyn-resolution one but it just crashes the game after you press A after game logo :-(

**Comment by stromcon** [comment]
I'm closing this issue, github is not the right place to do support for your Ryujinx installation. You may add in the discord (click on the logo in the top right) `ryu-support` channel or ask directly the mod creator.
